// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var App$Stuff = require("./App.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement(App$Stuff.make, {
          name: "Freddie"
        }), "root");

/*  Not a pure module */
